# Generated by Django 4.1.1 on 2022-10-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontact',
            name='bloodgroup',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createcontact',
            name='phoneno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='createcontact',
            name='workno',
            field=models.CharField(max_length=11),
        ),
    ]
